import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ApolloWrapperUsers } from "@/lib/users/ApolloWrapperUsers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapperUsers>{children}</ApolloWrapperUsers>
      </body>
    </html>
  );
}
