# user.gql

type Profile {
  id: String
  name: String
  user: User!
}

type Query {
  profiles: [Profile]
}

type Mutation {
  createProfile(name: String!, user: User!): Profile
  updateProfile(id: String!, name: String!, user: User!): Profile
  deleteProfile(id: String!): Profile
}
