# user.gql

type Profile {
  id: String
  name: String
  user: User!
}

type Query {
  profiles: [Profile]
}

input UserInput {
  id: String
  email: String!
  name: String
}

input UpdateProfileInput {
  id: String!, 
  name: String!, 
  user: UserInput!
}

input CreateProfileInput {
  name: String!, 
  user: UserInput!
}

type Mutation {
  createProfile(input: CreateProfileInput): Profile
  updateProfile(input: UpdateProfileInput): Profile
  deleteProfile(id: String!): Profile
}
