# user.gql

type Profile {
  id: String
  name: String
  user: User!
}

type Query {
  profiles: [Profile]
  profileById(id: String!): Profile
}

input UserCreateProfileInput {
  id: String!
}

input UpdateProfileInput {
  id: String!, 
  name: String!, 
  user: UserCreateProfileInput!
}

input CreateProfileInput {
  name: String!, 
  user: UserCreateProfileInput!
}

type Mutation {
  createProfile(input: CreateProfileInput): Profile
  updateProfile(input: UpdateProfileInput): Profile
  deleteProfile(id: String!): Profile
}
