# book.gql

type Product {
  id: Int
  label: String
  description: String
  price: Int
  image: String
  user: String
}

type Query {
  products: [Product]
}

input CreateProductArgs{
  label: String
  description: String
  price: Int
  image: String
  user: String
}

input UpdateProductArgs{
  id: Int!
  label: String
  description: String
  price: Int
  image: String
  user: String
}

type Mutation {
  addProduct(args: CreateProductArgs!): Product
  updateProduct(args: UpdateProductArgs!): Product
}
